#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Load nvm if it exists
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
# As a fallback, try loading from common nvm installation path
[ -s "$HOME/.nvm/nvm.sh" ] && \. "$HOME/.nvm/nvm.sh"

npm run lint
